[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts =
  pre:scripts/load_env.py
build_flags =
  -DWIFI_SSID=\"TU_SSID_WIFI\"
  -DWIFI_PASSWORD=\"TU_PASSWORD_WIFI\"
lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.5
  milesburton/DallasTemperature @ ^3.11.0
  paulstoffregen/OneWire @ ^2.3.8
