-- PASO 1: tabla de comandos para polling REST
-- Ejecuta este script en el SQL Editor de Supabase.

create table if not exists public.comandos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  accion text not null,
  sensor_id text not null,
  estado text not null default 'pendiente',
  constraint comandos_estado_check check (estado in ('pendiente', 'completado'))
);

create index if not exists idx_comandos_sensor_estado_created_at
  on public.comandos (sensor_id, estado, created_at desc);

alter table public.comandos enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update on table public.comandos to authenticated;
grant usage, select on sequence public.comandos_id_seq to authenticated;

drop policy if exists "authenticated can insert comandos" on public.comandos;
drop policy if exists "public can insert comandos" on public.comandos;
create policy "authenticated can insert comandos"
on public.comandos
for insert
to authenticated
with check (
  accion = 'forzar_lectura'
  and sensor_id in ('pecera_1', 'pecera_2')
  and estado = 'pendiente'
);

drop policy if exists "authenticated can read comandos" on public.comandos;
drop policy if exists "public can read comandos" on public.comandos;
create policy "authenticated can read comandos"
on public.comandos
for select
to authenticated
using (true);

drop policy if exists "authenticated can update comandos" on public.comandos;
drop policy if exists "public can update comandos" on public.comandos;
create policy "authenticated can update comandos"
on public.comandos
for update
to authenticated
using (sensor_id in ('pecera_1', 'pecera_2'))
with check (
  accion = 'forzar_lectura'
  and sensor_id in ('pecera_1', 'pecera_2')
  and estado in ('pendiente', 'completado')
);
