-- Ejecuta este script en el SQL Editor de Supabase.
-- Crea la tabla si aun no existe y genera mock data de las ultimas 48 horas.

create table if not exists public.temperaturas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  valor_temp double precision not null,
  sensor_id text not null
);

create index if not exists idx_temperaturas_created_at
  on public.temperaturas (created_at asc);

create index if not exists idx_temperaturas_sensor_id
  on public.temperaturas (sensor_id);

alter table public.temperaturas enable row level security;

grant usage on schema public to anon, authenticated;
grant select on table public.temperaturas to anon, authenticated;
grant insert on table public.temperaturas to anon;
grant usage, select on sequence public.temperaturas_id_seq to anon;

drop policy if exists "anon can insert temperaturas" on public.temperaturas;
create policy "anon can insert temperaturas"
on public.temperaturas
for insert
to anon
with check (true);

drop policy if exists "public can read temperaturas" on public.temperaturas;
create policy "public can read temperaturas"
on public.temperaturas
for select
to anon, authenticated
using (true);

delete from public.temperaturas
where sensor_id = 'sensor-demo-001'
  and created_at >= now() - interval '2 days';

with serie as (
  select generate_series(
    date_trunc('minute', now() - interval '47 hours 45 minutes'),
    date_trunc('minute', now()),
    interval '15 minutes'
  ) as ts
)
insert into public.temperaturas (created_at, valor_temp, sensor_id)
select
  ts,
  round(
    (
      26.8
      + sin(extract(epoch from ts) / 21600) * 0.9
      + (random() - 0.5) * 0.6
    )::numeric,
    2
  )::double precision as valor_temp,
  'sensor-demo-001' as sensor_id
from serie
order by ts;
