-- PASO 1: Backend en Supabase
-- Ejecuta este script completo en el SQL Editor de Supabase.
-- Crea la tabla `temperaturas`, activa RLS y permite:
-- 1) inserciones anónimas desde el ESP32
-- 2) lectura pública desde la web

create table if not exists public.temperaturas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  valor_temp double precision not null,
  sensor_id text not null
);

-- Indices simples para consultas por tiempo e identificación del sensor.
create index if not exists idx_temperaturas_created_at
  on public.temperaturas (created_at desc);

create index if not exists idx_temperaturas_sensor_id
  on public.temperaturas (sensor_id);

alter table public.temperaturas enable row level security;

-- Permisos mínimos para exponer la tabla a la API REST.
grant usage on schema public to anon, authenticated;
grant select on table public.temperaturas to anon, authenticated;
grant insert on table public.temperaturas to anon;
grant usage, select on sequence public.temperaturas_id_seq to anon;

drop policy if exists "anon can insert temperaturas" on public.temperaturas;
create policy "anon can insert temperaturas"
on public.temperaturas
for insert
to anon
with check (
  sensor_id in ('pecera_1', 'pecera_2', 'sensor-demo-001')
  and valor_temp between 0 and 60
  and created_at >= now() - interval '1 day'
  and created_at <= now() + interval '10 minutes'
);

drop policy if exists "public can read temperaturas" on public.temperaturas;
create policy "public can read temperaturas"
on public.temperaturas
for select
to anon, authenticated
using (true);
