-- Bootstrap de primera ejecucion
-- Deja listo el proyecto para que la web pueda mostrar datos desde el primer arranque.

-- =========================
-- Tabla: temperaturas
-- =========================
create table if not exists public.temperaturas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  valor_temp double precision not null,
  sensor_id text not null
);

create index if not exists idx_temperaturas_created_at
  on public.temperaturas (created_at asc);

create index if not exists idx_temperaturas_sensor_id
  on public.temperaturas (sensor_id);

alter table public.temperaturas enable row level security;

grant usage on schema public to anon, authenticated;
grant select on table public.temperaturas to anon, authenticated;
grant insert on table public.temperaturas to anon;
grant usage, select on sequence public.temperaturas_id_seq to anon;

drop policy if exists "anon can insert temperaturas" on public.temperaturas;
create policy "anon can insert temperaturas"
on public.temperaturas
for insert
to anon
with check (true);

drop policy if exists "public can read temperaturas" on public.temperaturas;
create policy "public can read temperaturas"
on public.temperaturas
for select
to anon, authenticated
using (true);

-- =========================
-- Tabla: comandos
-- =========================
create table if not exists public.comandos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  accion text not null,
  sensor_id text not null,
  estado text not null default 'pendiente',
  constraint comandos_estado_check check (estado in ('pendiente', 'completado'))
);

create index if not exists idx_comandos_sensor_estado_created_at
  on public.comandos (sensor_id, estado, created_at desc);

alter table public.comandos enable row level security;

grant select, insert, update on table public.comandos to anon, authenticated;
grant usage, select on sequence public.comandos_id_seq to anon, authenticated;

drop policy if exists "public can insert comandos" on public.comandos;
create policy "public can insert comandos"
on public.comandos
for insert
to anon, authenticated
with check (estado in ('pendiente', 'completado'));

drop policy if exists "public can read comandos" on public.comandos;
create policy "public can read comandos"
on public.comandos
for select
to anon, authenticated
using (true);

drop policy if exists "public can update comandos" on public.comandos;
create policy "public can update comandos"
on public.comandos
for update
to anon, authenticated
using (true)
with check (estado in ('pendiente', 'completado'));

-- =========================
-- Mock data inicial
-- =========================
delete from public.temperaturas
where sensor_id in ('sensor-demo-001', 'pecera_1')
  and created_at >= now() - interval '2 days';

with serie as (
  select generate_series(
    date_trunc('minute', now() - interval '47 hours 45 minutes'),
    date_trunc('minute', now()),
    interval '15 minutes'
  ) as ts
)
insert into public.temperaturas (created_at, valor_temp, sensor_id)
select
  ts,
  round(
    (
      25.4
      + sin(extract(epoch from ts) / 21600) * 0.8
      + (random() - 0.5) * 0.5
    )::numeric,
    2
  )::double precision as valor_temp,
  'pecera_1' as sensor_id
from serie
order by ts;
